language: c
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo update-alternatives --config gcc
  - cd /tmp && wget http://igraph.org/nightly/get/c/igraph-0.7.1.tar.gz && tar -xvzf igraph-0.7.1.tar.gz && cd igraph-0.7.1 && ./configure && make && sudo make install && sudo ldconfig

script:
  - cd $TRAVIS_BUILD_DIR
  - make
  - ./graphpass

after_success:
  - bash <(curl -s https://codecov.io/bash)
